### ISSUE TITLE
Time breaks to multiple lines at 320 px

### ISSUE THREAD

**Issue by thomasjbradley** [algonquindesign-grads/2019-coming-soon#2]
If you remove the `.gutter-1-2` from the parent element it can fit on the same line.

![screen shot 2019-02-03 at 12 49 06 pm](https://user-images.githubusercontent.com/105192/52180283-3ea25a00-27b2-11e9-8bb5-d55a4f85e8a3.png)

**Comment by RaquelAlves01** [comment]
Fixed
